name: iOS starter workflow

on: workflow_dispatch # so manually run on my test branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Configure Git for private repo
        run: git config --global url."https://${{ secrets.CH_IOS_AUTOMATED }}@github.com/".insteadOf "https://github.com/"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Build
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          # xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          xcodebuild build-for-testing -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device" OTHER_SWIFT_FLAGS="-DQA_TESTING"
      #- name: Test
      #  env:
      #    scheme: ${{ 'default' }}
      #    platform: ${{ 'iOS Simulator' }}
      #  run: |
      #    # xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
      #    device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
      #    if [ $scheme = default ]; then scheme=$(cat default); fi
      #    if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
      #    file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
      #    xcodebuild test-without-building -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device"

      - name: Upload file to Egnyte
        env:
          EGNYTE_API_KEY: ${{ secrets.EGNYTE_API_KEY }}
          EGNYTE_DOMAIN: epicore.egnyte.com
          EGNYTE_DESTINATION_FOLDER: Shared/Shared%20Files%20-%20PUBLIC/CH_Automated_Builds
          SOURCE_FOLDER: Build/Products/Release-iphoneos # The local folder to upload

        run: |
          # Get a list of all files in the source folder
          FILES=$(find "$SOURCE_FOLDER" -type f)

          # Loop through each file and upload it
          for FILE in $FILES; do
            # Construct the Egnyte path
            EGNYTE_FILE_PATH="$EGNYTE_DESTINATION_FOLDER/${FILE#$SOURCE_FOLDER/}"
            
            # URL-encode the file path
            URL_ENCODED_PATH=$(echo "$EGNYTE_FILE_PATH" | sed 's/ /%20/g')

            echo "Uploading $FILE to $EGNYTE_FILE_PATH"
            curl -X POST \
              "https://$EGNYTE_DOMAIN/pubapi/v1/fs-content/$URL_ENCODED_PATH" \
              -H "Authorization: Bearer $EGNYTE_API_KEY" \
              -H "Content-Type: application/octet-stream" \
              --data-binary "@$FILE"
          done
